#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/mother3.h"
#include "images/saladrom2.h"
#include "images/title.h"
#include "images/RSE_Strength.h"
#include "images/HM04.h"
#include "images/tent.h"
#include "images/blackmage1.h"
#include "images/blackmage2.h"


#include "logic.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  Player player234 = {96, 96, 16, 16};
  Player old_player = {96, 96, 16, 16};

  Player *p1 = &player234; 
  Player *oldplayer = &old_player;
  // Load initial application state
  enum gba_state state = HEALTH;
  enum gba_state *stateptr = &state;

  int frame = 0;
  int frameCount = 0;
  int time;
  int init = 0;
  // Rock levelOne[] = {{0, 0, 16, 16}, {0, 16, 16, 16}, {0, 32, 16, 16}, {0, 48, 16, 16}, {0, 64 , 16, 16}, {0, 80, 16, 16}, {0, 96, 16, 16}, {0, 112, 16, 16}, {0, 128 , 16, 16}, {0, 144, 16, 16}, {0, 160, 16, 16}, {0, 176, 16, 16}, {0, 192, 16, 16},{0, 208, 16, 16},{0, 224 , 16, 16},{0, 240, 16, 16},
  //                   {16, 0, 16, 16}, {16, 16, 16, 16}, {16, 32, 16, 16}, {16, 48, 16, 16}, {16, 64, 16, 16}, {16, 80, 16, 16}, {16, 96, 16, 16}, {16, 112, 16, 16}, {16, 128, 16, 16}, {16, 144, 16, 16}, {16, 160, 16, 16}, {16, 176, 16, 16}, {16, 192, 16, 16}, {16, 208, 16, 16}, {16, 224, 16, 16}, {16, 240, 16, 16}, 
  //                   {32, 0, 16, 16}, {32, 16, 16, 16},{32, 32, 16, 16}, {32, 48, 16, 16}, {32, 64, 16, 16},{32, 80, 16, 16}, {32, 96, 16, 16}, {32, 112, 16, 16},{32, 128, 16, 16}, {32, 144, 16, 16}, {32, 160, 16, 16},{32, 176, 16, 16}, {32, 192, 16, 16}, {32, 208, 16, 16},{32, 224, 16, 16}, {32, 240, 16, 16}, 
  //                   {48, 0, 16, 16},{48, 16, 16, 16}, {48, 32, 16, 16}, {48, 48, 16, 16},{48, 64, 16, 16}, {48, 80, 16, 16}, {48, 96, 16, 16},{48, 112, 16, 16}, {48, 128, 16, 16}, {48, 144, 16, 16},{48, 160, 16, 16}, {48, 176, 16, 16}, {48, 192, 16, 16},{48, 208, 16, 16}, {48, 224, 16, 16}, {48, 240, 16, 16},
  //                   {64, 0, 16, 16}, {64, 16, 16, 16}, {64, 32, 16, 16}, {64, 48, 16, 16}, {64, 64, 16, 16}, {64, 80, 16, 16}, {64, 96, 16, 16}, {64, 112, 16, 16}, {64, 128, 16, 16}, {64, 144, 16, 16}, {64, 160, 16, 16}, {64, 176, 16, 16}, {64, 192, 16, 16}, {64, 208, 16, 16}, {64, 224, 16, 16}, {64, 240, 16, 16}, 
  //                   {80, 0, 16, 16}, {80, 16, 16, 16}, {80, 32, 16, 16}, {80, 48, 16, 16}, {80, 64, 16, 16}, {80, 80, 16, 16}, {80, 96, 16, 16}, {80, 112, 16, 16}, {80, 128, 16, 16}, {80, 144, 16, 16}, {80, 160, 16, 16}, {80, 176, 16, 16}, {80, 192, 16, 16}, {80, 208, 16, 16}, {80, 224, 16, 16}, {80, 240, 16, 16}, {96, 0, 16, 16},
  //                   {96, 0, 16, 16}, {96, 16, 16, 16},{96, 32, 16, 16}, {96, 48, 16, 16}, {96, 64, 16, 16},{96, 80, 16, 16}, {96, 96, 16, 16}, {96, 112, 16, 16},{96, 128, 16, 16}, {96, 144, 16, 16}, {96, 160, 16, 16},{96, 176, 16, 16}, {96, 192, 16, 16}, {96, 208, 16, 16},{96, 224, 16, 16}, {96, 240, 16, 16}, 
  //                   {112, 0, 16, 16},{112, 16, 16, 16}, {112, 32, 16, 16}, {112, 48, 16, 16},{112, 64, 16, 16}, {112, 80, 16, 16}, {112, 96, 16, 16},{112, 112, 16, 16}, {112, 128, 16, 16}, {112, 144, 16, 16},{112, 160, 16, 16}, {112, 176, 16, 16}, {112, 192, 16, 16},{112, 208, 16, 16}, {112, 224, 16, 16}, {112, 240, 16, 16},
  //                   {128, 0, 16, 16}, {128, 16, 16, 16}, {128, 32, 16, 16}, {128, 48, 16, 16}, {128, 64, 16, 16}, {128, 80, 16, 16}, {128, 96, 16, 16}, {128, 112, 16, 16}, {128, 128, 16, 16}, {128, 144, 16, 16}, {128, 160, 16, 16}, {128, 176, 16, 16}, {128, 192, 16, 16}, {128, 208, 16, 16}, {128, 224, 16, 16}, {128, 240, 16, 16}, 
  //                   {144, 0, 16, 16}, {144, 16, 16, 16}, {144, 32, 16, 16}, {144, 48, 16, 16}, {144, 64, 16, 16}, {144, 80, 16, 16}, {144, 96, 16, 16}, {144, 112, 16, 16}, {144, 128, 16, 16}, {144, 144, 16, 16}, {144, 160, 16, 16}, {144, 176, 16, 16}, {144, 192, 16, 16}, {144, 208, 16, 16}, {144, 224, 16, 16}, {144, 240, 16, 16}};
  Rock levelOne[] =  {{0, 16, 16, 16}, {0, 144, 16, 16}, //{0, 160, 16, 16}, {0, 176, 16, 16}, //{0, 192, 16, 16},{0, 208, 16, 16},{0, 224 , 16, 16},{0, 240, 16, 16},
                     {16, 16, 16, 16}, {16, 32, 16, 16}, {16, 144, 16, 16},// {16, 160, 16, 16}, {16, 176, 16, 16}, //{16, 192, 16, 16}, {16, 208, 16, 16}, {16, 224, 16, 16}, {16, 240, 16, 16}, 
                     {32, 16, 16, 16},{32, 32, 16, 16}, {32, 144, 16, 16}, //{32, 160, 16, 16},{32, 176, 16, 16}, //{32, 192, 16, 16}, {32, 208, 16, 16},{32, 224, 16, 16}, {32, 240, 16, 16}, 
                     {32, 16, 16, 16},{32, 32, 16, 16}, {48, 144, 16, 16},//{48, 160, 16, 16}, {48, 176, 16, 16}, //{48, 192, 16, 16},{48, 208, 16, 16}, {48, 224, 16, 16}, {48, 240, 16, 16},
                    {48, 16, 16, 16}, {48, 32, 16, 16}, {64, 144, 16, 16}, //{64, 160, 16, 16}, {64, 176, 16, 16}, //{64, 192, 16, 16}, {64, 208, 16, 16}, {64, 224, 16, 16}, {64, 240, 16, 16}, 
                    {64, 16, 16, 16}, {64, 32, 16, 16}, {80, 144, 16, 16}, //{80, 160, 16, 16}, {80, 176, 16, 16}, //{80, 192, 16, 16}, {80, 208, 16, 16}, {80, 224, 16, 16}, {80, 240, 16, 16}, {96, 0, 16, 16},
                    {96, 16, 16, 16},{96, 32, 16, 16}, {112, 144, 16, 16}, //{112, 160, 16, 16}, {112, 176, 16, 16}, //{112, 192, 16, 16}, {112, 208, 16, 16}, {112, 224, 16, 16}, {112, 240, 16, 16},
                     {112, 16, 16, 16}, {112, 32, 16, 16}, {128, 144, 16, 16}, //{128, 160, 16, 16}, {128, 176, 16, 16}, //{128, 192, 16, 16}, {128, 208, 16, 16}, {128, 224, 16, 16}, {128, 240, 16, 16}, 
                     {128, 16, 16, 16}, {128, 32, 16, 16}, {144, 144, 16, 16}, //{144, 160, 16, 16}, {144, 176, 16, 16}, {144, 192, 16, 16},
                    {80, 16, 16, 16}, {80, 32, 16, 16}, {96, 144, 16, 16},
                    {0, 128, 16, 16}, {16, 128, 16, 16}, {32, 128, 16, 16}, {48, 128, 16, 16}, {64, 128, 16, 16}, {80, 128, 16, 16}, {96, 128, 16, 16}, {112, 128, 16, 16}, {128, 128, 16, 16}, {144, 128, 16, 16}, {0, 80, 16, 16},
                    {144, 0, 16, 16}, {144, 16, 16, 16}, {144, 32, 16, 16}, {16, 48, 16, 16}, {16, 112, 16, 16}, {0, 64, 16, 16}, {0, 96, 16, 16},
                    {32, 48, 16, 16}, {32, 64, 16, 16}, {32, 96, 16, 16}, {32, 112, 16, 16}, 
                    {48, 64, 16, 16}, {48, 80, 16, 16}, {48, 96, 16, 16},
                    {64, 48, 16, 16}, {64, 112, 16, 16},
                    {80, 64, 16, 16}, {80, 80, 16, 16}, {80, 96, 16, 16},};

  Rock levelTwo[] = {{0, 0, 16, 16}, {0, 16, 16, 16}, {0, 32, 16, 16}, {0, 48, 16, 16}, {0, 64 , 16, 16}, {0, 80, 16, 16}, {0, 96, 16, 16}, {0, 112, 16, 16}, {0, 128 , 16, 16}, {0, 144, 16, 16}, {0, 160, 16, 16}, {0, 176, 16, 16}, {0, 192, 16, 16},{0, 208, 16, 16},{0, 224 , 16, 16},{0, 240, 16, 16},
                    {16, 0, 16, 16}, {16, 16, 16, 16}, {16, 32, 16, 16}, {16, 48, 16, 16}, {16, 64, 16, 16}, {16, 80, 16, 16}, {16, 96, 16, 16}, {16, 112, 16, 16}, {16, 128, 16, 16}, {16, 144, 16, 16}, {16, 160, 16, 16}, {16, 176, 16, 16}, {16, 192, 16, 16}, {16, 208, 16, 16}, {16, 224, 16, 16}, {16, 240, 16, 16}, 
                    {32, 0, 16, 16}, {32, 16, 16, 16},{32, 32, 16, 16}, {32, 48, 16, 16}, {32, 64, 16, 16},{32, 80, 16, 16}, {32, 96, 16, 16}, {32, 112, 16, 16},{32, 128, 16, 16}, {32, 144, 16, 16}, {32, 160, 16, 16},{32, 176, 16, 16}, {32, 192, 16, 16}, {32, 208, 16, 16},{32, 224, 16, 16}, {32, 240, 16, 16}, 
  
                    {112, 0, 16, 16},{112, 16, 16, 16}, {112, 32, 16, 16}, {112, 48, 16, 16},{112, 64, 16, 16}, {112, 80, 16, 16}, {112, 96, 16, 16},{112, 112, 16, 16}, {112, 128, 16, 16}, {112, 144, 16, 16},{112, 160, 16, 16}, {112, 176, 16, 16}, {112, 192, 16, 16},{112, 208, 16, 16}, {112, 224, 16, 16}, {112, 240, 16, 16},
                    {128, 0, 16, 16}, {128, 16, 16, 16}, {128, 32, 16, 16}, {128, 48, 16, 16}, {128, 64, 16, 16}, {128, 80, 16, 16}, {128, 96, 16, 16}, {128, 112, 16, 16}, {128, 128, 16, 16}, {128, 144, 16, 16}, {128, 160, 16, 16}, {128, 176, 16, 16}, {128, 192, 16, 16}, {128, 208, 16, 16}, {128, 224, 16, 16}, {128, 240, 16, 16}, 
                    {144, 0, 16, 16}, {144, 16, 16, 16}, {144, 32, 16, 16}, {144, 48, 16, 16}, {144, 64, 16, 16}, {144, 80, 16, 16}, {144, 96, 16, 16}, {144, 112, 16, 16}, {144, 128, 16, 16}, {144, 144, 16, 16}, {144, 160, 16, 16}, {144, 176, 16, 16}, {144, 192, 16, 16}, {144, 208, 16, 16}, {144, 224, 16, 16}, {144, 240, 16, 16},
                    {96, 96, 16, 16}};
  Rock initialLevelOne[200];
  Rock initialLevelTwo[200];
  int levelOneLength = sizeof(levelOne) / sizeof(levelOne[0]);
  int levelTwoLength = sizeof(levelTwo) / sizeof(levelTwo[0]);
  struct object Hidden_Machine = {0, 0, 16, 16};
  while (1) {
    frame++;
    waitForVBlank();    
    currentButtons = BUTTONS; // Load the current state of the buttons
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      resetGameState(p1, oldplayer, levelOne, initialLevelOne, stateptr, &init, &frame, &frameCount, levelOneLength, initialLevelTwo, levelTwo, levelTwoLength);
    }
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case HEALTH:
        if (init == 0) {
          drawFullScreenImageDMA(mother3);
          init = 1;
        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
         {
          state = START;
          init = 0;
        }
        break;
      case START:
        if (init == 0)
        {
          drawFullScreenImageDMA(tiele);
          drawImageDMA(0, 0, BLACKMAGEVICTORY1_WIDTH, BLACKMAGEVICTORY1_HEIGHT, BlackMageVictory1);
          init = 1;
        }

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
        {
          state = LEVEL1;
          init = 0;
        }
        animation(frame);
        break;
      case LEVEL1:
        frameCount++;
        time = frameCount / 60;
        char buffer[41];
        sprintf(buffer, "Time: %d", time);
        if (init == 0) {
          player234.row = 96;
          player234.column = 96;
          old_player.row = 96;
          old_player.column = 96;
          Hidden_Machine.row = 0;
          Hidden_Machine.column = 80;
          drawRectDMA(0, 0, 240, 160, BLACK);
          drawRectDMA(0, 32, 16, 160, WHITE);
          drawRectDMA(0, 128, 16, 160, WHITE);
          drawImageDMA(Hidden_Machine.row, Hidden_Machine.column, 16, 16, HM04);
          for (int i = 0; i < levelOneLength; i++)
          {
            if (i > levelOneLength - 17)
            {
              drawImageDMA(levelOne[i].row, levelOne[i].column, 16, 16, RSE_Strength);
            }
            initialLevelOne[i].row = levelOne[i].row;
            initialLevelOne[i].column = levelOne[i].column;
            initialLevelOne[i].width = levelOne[i].width;
            initialLevelOne[i].height = levelOne[i].height;
          }
          init = 1;
        }
        drawRectDMA(140, 145, 100, 20, BLACK);
        drawString(148, 150, buffer, WHITE);
        playermovement(oldplayer, p1, currentButtons, &frame, levelOne, Hidden_Machine, levelOneLength, stateptr);
        if (state == LEVEL2)
        {
          frameCount = 0;
          init = 0;
          state = WIN;
          break;
        }
        break;
        // state = ?
      case LEVEL2:
        frameCount++;
        time = frameCount / 60;
        char buffer2[41];
        sprintf(buffer2, "Time: %d", time);
        if (init == 0) {
          p1->row = 64;
          p1->column = 16;
          oldplayer->row = 64;
          oldplayer->column = 16;
          Hidden_Machine.row = 64;
          Hidden_Machine.column = 224;
          drawRectDMA(0, 0, 240, 160, BLACK);
          drawRectDMA(0, 0, 240, 48, WHITE);
          drawRectDMA(112, 0, 240, 60, WHITE);
          drawImageDMA(Hidden_Machine.row, Hidden_Machine.column, 16, 16, HM04);
          for (int i = 0; i < levelTwoLength; i++)
          {
            if (i > levelTwoLength - 2)
            {
              drawImageDMA(levelTwo[i].row, levelTwo[i].column, 16, 16, RSE_Strength);
            }
            initialLevelTwo[i].row = levelTwo[i].row;
            initialLevelTwo[i].column = levelTwo[i].column;
            initialLevelTwo[i].width = levelTwo[i].width;
            initialLevelTwo[i].height = levelTwo[i].height;
          }
          
          init = 1;
        }
        drawRectDMA(140, 145, 100, 20, BLACK);
        drawString(148, 150, buffer2, WHITE);
        playermovement(oldplayer, p1, currentButtons, &frame, levelTwo, Hidden_Machine, levelTwoLength, stateptr);
        break;
      case WIN:
        drawFullScreenImageDMA(saladrom21);
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
  return 0;
}
